version: "3.7"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - /var/transerve/docker/volumes/redis:/data
  zookeeper:
    image: "fogsyio/zookeeper:3.4.13"
    ports:
      - "2181:2181"
    environment:
      - "ALLOW_ANONYMOUS_LOGIN=yes"
  kafka:
    image: "fogsyio/kafka:2.2.0"
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - "KAFKA_BROKER_ID=1"
      - "KAFKA_LISTENERS=PLAINTEXT://:9092"
      - "KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092"
      - "KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181"
      - "ALLOW_PLAINTEXT_LISTENER=yes"
    depends_on:
      - zookeeper
  postgres:
    image: "postgres:9.6"
    container_name: postgres
    command: postgres -c 'max_connections=200'
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=oddb"
    ports:
      - "5432:5432"
    volumes:
      - "/var/transerve/docker/volumes/postgres:/var/lib/postgresql/data"
  egov-accesscontrol:
    container_name: egov-accesscontrol
    image: "egov-accesscontrol"
    ports:
      - "8091:8091"
  egov-filestore:
    container_name: egov-filestore
    image: "egov-filestore"
    ports:
      - "8060:8060"    
  egov-localization:
    container_name: egov-localization
    image: "egov-localization"
    ports:
      - "8087:8087"
  egov-mdms-service:
    container_name: egov-mdms-service
    image: "egov-mdms-service"
    ports:
      - "8094:8094"    
  egov-otp:
    container_name: egov-otp
    image: "egov-otp"
    ports:
      - "8089:8089"   
  egov-persister:
    container_name: egov-persister
    image: "egov-persister"
    ports:
      - "8082:8082"    
    depends_on:
      - kafka
  egov-user:
    container_name: egov-user
    image: "egov-user"
    ports:
      - "8085:8085"    
    depends_on:
      - egov-mdms-service
  egov-workflow-v2:
    container_name: egov-workflow-v2
    image: "egov-workflow-v2"
    ports:
      - "8099:8099"    
  user-otp:
    container_name: user-otp
    image: "user-otp"
    ports:
      - "8090:8090"    
  zuul:
    container_name: zuul
    image: "zuul"
    ports:
      - "9123:8083"
  egov-idgen:
    container_name: egov-idgen
    image: "egov-idgen"
    ports:
      - "8088:8088"    
  billing-service:
    container_name: billing-service
    image: "billing-service"
    ports:
      - "8988:8988"    
  property-services:
    container_name: property-services
    image: "property-services"
    ports:
      - "8270:8270"    
    depends_on:
      - kafka
  egov-enc-service:
    container_name: egov-enc-service
    image: "egov-enc-service"
    ports:
      - "8071:8071"    
  tl-services:
    container_name: tl-services
    image: "tl-services"
  tl-calculator:
    container_name: tl-calculator
    image: "tl-calculator"
  egov-location:
    container_name: egov-location
    image: "egov-location"
    ports:
      - "8097:8097"    
  collection-services:
    container_name: collection-services
    image: "collection-services"
    ports:
      - "8280:8280"    
  # sw-services:
  #   container_name: sw-services
  #   image: "sw-services"
  # ws-services:
  #   container_name: ws-services
  #   image: "ws-services"
volumes:
  kafka: